services: 
  app: 
    build: 
      context: .
      dockerfile: ./Dockerfile
  ports: 
    - ":"
  env_file: 
    - ./config/config.yml
  restart:
    always
  
  nginx: 
    image: nginx:latest
    ports: 
      - "80:80"
    
  
