name: Test

on: 
    pull_request:

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Set up Golang
              uses: actions/setup-go@v4
              with:
                go-version: '1.22.3'
            # - name: Install deps
            #   run: go mod tidy
            # - name: Build 
            #   run: go build -o main.exe .\cmd\main.go 
            # - name: Test
            #   run: go test
        