name: Test

on:
    push:
        branches:
            ['main']
    pull_request:
        branches:
            ['main']

jobs: 
    build: 
        runs-on: ubuntu-22.04
        steps: 
            - uses: actions/checkout@v4
            - name: Set up Golang
              uses: actions/setup-go@v4
              with:
                go-version: '1.22.3'
            - name: Install deps
              run: go mod tidy
            # - name: Build 
            #   run: go build -o main.exe .\cmd\main.go 
            # - name: Test
            #   run: go test
        